### ISSUE TITLE
Binary sensors working until HA restart

### ISSUE THREAD

**Issue by tetragram55** [elad-bar/ha-blueiris#28] opened 2020-02-17 01:11 UTC
I had this working nice.
And then I did a restart on Homeassistant. It created a new set of sensors with a _2 suffix.
I cleaned it up and removed everything and started over.
I reinstalled and it went okay and everything is there again but none of the sensors work in the home assistant user interface.
The camera views work just not the sensors.

They show up in mqtt but won't trigger in home assistant.
Here is a copy of what happens when I move in front of the camera: 

HiveMQ Messages:
2020-02-16 17:07:10Topic: BlueIris/Cam2/StatusQos: 2{ "type": "MOTION_A", "trigger": "OFF" }
2020-02-16 17:06:57Topic: BlueIris/Cam2/StatusQos: 2{ "type": "MOTION_A", "trigger": "ON" }
2020-02-16 17:06:55Topic: BlueIris/Cam2/StatusQos: 2{ "type": "MOTION_A", "trigger": "ON" }
2020-02-16 17:06:54Topic: BlueIris/Cam2/StatusQos: 2{ "type": "MOTION_A", "trigger": "ON" }
2020-02-16 17:06:49Topic: BlueIris/Cam2/StatusQos: 2{ "type": "MOTION_A", "trigger": "ON" }
2020-02-16 17:06:34Topic: BlueIris/appQos: 2Retainedunexpected stop

Let me know what I can do to help you help me troubleshoot this,
Thanks!

**Comment by kzaoaai** [comment] 2020-02-21 00:14
Same issue for me. MQTT shows the correct messages, but the HA binary_sensors don't change state from off.

**Comment by cbuxton5200** [comment] 2020-02-23 18:45
I think I have a similar issue, I installed the integration and successfully added my server to the configuration.  I can add the entities to a lovelace card and view the camera stream, however, I am not getting any state change on the motion detection binary sensor.  Any thing I can check?  I have uninstalled and reinstalled, but it doesn't change.

**Comment by elad-bar** [comment] 2020-02-23 18:47
I'm working on a fix for that issue, will take few more days to fix and test,
Will update

**Comment by Linwood-F** [comment] 2020-02-24 17:05
If you need someone to test, I am just starting to get BlueIris going with HA, so no real loss if I break something.

**Comment by webwhiz** [comment] 2020-02-24 20:29
I have the same issue. Never got it sensors working. I know from mqtt addon logs, blueiris connects to the broker but sensors are not updated on dashboard. will wait for the fix. thanks.

**Comment by Linwood-F** [comment] 2020-02-28 16:30
I'm not seeing this working, still after the last change.  As an example, I have a camera camDriveway in BlueIris.  To confirm BlueIris is set up right, I defined this test sensor manually: 

      - platform: mqtt
        name: camDriveway Motion
        device_class: motion
        state_topic: "BlueIris/camDriveway/Status"
        value_template: "{{ value_json['trigger'] }}"

Again, this was just a test, but this works perfectly - if I trigger in BlueIris this goes on, then a bit later off.

But the automatically generated sensor binary_sensor.blueiris_camdriveway_motion that comes from the integration does not change after installing the new update and restarting HA.

I tried deleting the integration and adding it again, restarted HA, same result. 

I'm on 0.106.0 and the commit referenced above.

**Comment by elad-bar** [comment] 2020-02-28 17:08
can you post the log of MQTT, I would like to reproduce the same messages on my system to understand it better

thanks

**Comment by Linwood-F** [comment] 2020-02-28 17:16
I apologise for the lack of familiarity, is this a log I would get from HA?  Perhaps with a config yaml setting?  I can run MQTT_Explorer as well, but it's more of a real time display I think?

**Comment by elad-bar** [comment] 2020-02-28 17:20
I'm using MQTTBox (Windows 10) but you can use any other tool if you already have it,
Based on the progress of the investigation I might also need HA logs (but you can do it without changing the config YAML).

Developer -> Services -> find service named `logger.set_level` with the following data in the request:
custom_components.blueiris: debug

afterwards, you will need to remove the BlueIris integration and re-add it, 2 minutes afterward, you can take the logs zip it and post it

thanks

**Comment by Linwood-F** [comment] 2020-02-28 17:49
See if these help: 

[logs.zip](https://github.com/elad-bar/ha-blueiris/files/4268342/logs.zip)

This part is consistent I think:

    2020-02-28 12:42:03 DEBUG (MainThread) [custom_components.blueiris.binary_sensors.main] Received BlueIris Message - BlueIris/camDriveway/Status: { "type": "EXTERNAL", "trigger": "ON" }
    2020-02-28 12:42:03 DEBUG (MainThread) [custom_components.blueiris.home_assistant] Updating @None

Somehow the message just isn't connecting to the camera.

**Comment by elad-bar** [comment] 2020-02-28 17:52
External is not supported only:
* Audio
* Motion
* Connectivity (Watchdog)

By the way, external according to few forums is about to be replaced with the ONVIF option (which is also not supported)

**Comment by Linwood-F** [comment] 2020-02-28 17:55
OK, that's from a manual trigger in blue iris, but let me go walk it and see what happens... Give me a few...

**Comment by elad-bar** [comment] 2020-02-28 17:56
Configuration should look like:
![image](https://user-images.githubusercontent.com/3207137/75572875-52c39400-5a64-11ea-8a1b-9150db5c1cba.png)

**Comment by Linwood-F** [comment] 2020-02-28 18:00
That's what I have, but when you do this to test it appears to change it to external: 

![manualtrigger](https://user-images.githubusercontent.com/13143855/75573090-1a9f5f80-5a2a-11ea-895c-a653a4b1ba99.jpg)

And yes, if I actually walk it I get a detection.  Sorry for the confusion, I thought that the BI test trigger should show as well, since that's kind of what it is for in a way.  But now that I know, no issue I guess.

**Comment by elad-bar** [comment] 2020-02-28 18:02
use the MQTT Explorer or any other tool to publish events to see how the component reacts, that's how it test it

**Comment by elad-bar** [comment] 2020-02-29 12:10
can we close the issue?

**Comment by Linwood-F** [comment] 2020-02-29 14:13
From my perspective yes, sorry for the confusion.

**Comment by elad-bar** [comment] 2020-02-29 14:28
that's ok :)

**Closed by elad-bar** 2020-02-29 14:28 UTC
