### ISSUE TITLE
High BI CPU Usage When Intergration is Active. 

### ISSUE THREAD

**Issue by RJ-Make** [elad-bar/ha-blueiris#160] opened 2022-03-12 20:37 UTC
Not sure when this started but. 

I'm seeing significantly higher BlueIris CPU usage anytime the integration is enabled (after a HA restart) BI CPU consumption goes from a normal ~3% to a whoping ~35%. Once I shut the integration down (after a HA restart) BI CPU consumption returns to ~3%.

This is with no camera cards in Home Assistant. 

Windows 10 Pro, HAOS Running inside VirtualBox. 

## System Health

version | core-2022.3.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.98
arch | x86_64
timezone | America/New_York

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4918
Installed Version | 1.23.0
Stage | running
Available Repositories | 1008
Downloaded Repositories | 9

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | March 21, 2022, 8:00 PM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server |XX
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.03.3
docker_version | 20.10.9
disk_total | 30.8 GB
disk_used | 13.0 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), Studio Code Server (4.1.0), InfluxDB (4.3.0), File editor (5.3.3), Nextcloud Backup (0.16.8), SSH & Web Terminal (10.0.2), Samba Backup (5.0.0), Z-Wave JS (0.1.54), Z-Wave JS to MQTT (0.36.0), Network UPS Tools (0.9.1), MariaDB (2.4.0), Zigbee2mqtt (1.24.0-1)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 3
views | 7
mode | storage

</details>

**Comment by kramttocs** [comment] 2022-03-12 21:08
There must be some streaming going on somewhere. Otherwise the integration is just making json calls on a polling interval which wouldn't have that kind of CPU impact. Do you see the same behavior if you disable the integration and load up UI3 from Blue Iris?

**Comment by RJ-Make** [comment] 2022-03-12 23:21
Thanks for the suggestion. 

When I open UI3, I get a ~4% increase. 

This is what I know. 

1) The integration has it's own BI user credentials. If I disable that user in BI and restart HA, BI returns to normal CPU consumption. 

2) I have removed all UI cards containing a video stream, problem persists.

3) Disabling the integration does NOT reduce the high BI CPU consumption, I must restart HA to reduce the consumption.

Like something in the integration doesn't disconnect when disabled. Perhaps this is normal?

I have a feeling this is going to be a nightmare trying to diagnose.. 😥

**Comment by RJ-Make** [comment] 2022-03-12 23:22
I have to leave the integration disabled until I can figure this out.

**Comment by kramttocs** [comment] 2022-03-12 23:32
I agree - this one will likely be tough to track down. BI does show if a camera is loaded by the user so maybe that would give us some clue. I'll check CPU changes on my machine, hopefully tonight, to see if I notice a difference. Lot of factors though: # of cameras, quality of cameras, specs of BI server, etc.

**Comment by RJ-Make** [comment] 2022-03-13 11:34
As a BI CPU reference point (Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz   3.70 GHz)


<img width="765" alt="2022-03-13_7-08-19" src="https://user-images.githubusercontent.com/8496835/158057422-3b0807d7-05b3-4c89-862c-33dc04e32944.png">



<img width="1043" alt="2022-03-13_7-23-03" src="https://user-images.githubusercontent.com/8496835/158057429-9353acae-c748-4e5f-be0a-e6f152cd9eff.png">


<img width="758" alt="2022-03-13_6-55-27" src="https://user-images.githubusercontent.com/8496835/158057362-e0d36594-7845-4588-a196-453293dbaf26.png">


<img width="762" alt="2022-03-13_6-57-02" src="https://user-images.githubusercontent.com/8496835/158057372-c4b8bfac-da21-4322-adf6-940114d59346.png">


<img width="764" alt="2022-03-13_6-59-57" src="https://user-images.githubusercontent.com/8496835/158057414-b4bdcbc7-72d0-492d-8034-a2983912278a.png">


<img width="752" alt="2022-03-13_6-52-34" src="https://user-images.githubusercontent.com/8496835/158057378-cc6c208e-548b-467f-bcde-0e3689636592.png">


<img width="763" alt="2022-03-13_7-18-29" src="https://user-images.githubusercontent.com/8496835/158057383-e97568af-82e9-490b-95bb-d13faa61abbe.png">

**Comment by RJ-Make** [comment] 2022-03-13 20:37
I think I found what may be the cause.  I was thinking what would cause a 2 second cycle through all the camera's non-stop, then I remembered a month or so ago, I select the `Support stream component (Requires restart)` Option to test out, and then un-ticked it after messing around.  

Went back to the setting and it was un-ticked. So I re-ticked it, restarted, un-ticked it and restarted, same result. 

So today, I decided to completely wipe the integration off my system, then reinstalled and setup and now it's back running at a normal ~1% overhead. 

So it appears there may be a disconnect between the UI and wherever that setting lives. Assuming that setting causes the camera cycles.

**Comment by kramttocs** [comment] 2022-03-13 22:05
Nice work!
I haven't ever tried that feature but will make a note to. I have noticed the integration does seem to hold on to old deleted cameras so the root cause may be the same or similar. Will try to track that down.

**Comment by griffincorriher** [comment] 2022-03-19 13:43
Having the same issue, but the full removal and re-add did not solve it

**Comment by kramttocs** [comment] 2022-03-19 16:20
> Having the same issue, but the full removal and re-add did not solve it

Unfortunately too many variables in this one to guess at what might need changed in in the integration so can you do some troubleshooting and try to narrow it down? The BI log/connection status may give us some clues to identifying if yours is the same behavior (even if not the same resolution) as RJ-Make.

**Comment by griffincorriher** [comment] 2022-03-19 16:32
When I reinstalled today I used the previous version of the integration and my UPS load is back to normal for now.

**Comment by kramttocs** [comment] 2022-03-19 17:01
Which version is that?

**Comment by kramttocs** [comment] 2022-03-19 17:29
The Blue Iris Status > Connections will likely tell us the most.

For reference, here is a test I did just now.
1. Closed anything that was connected to HA actively (meaning nothing is viewing it via the browser or app)
2. Restarted the Blue Iris Service on my Windows Server
3. Opened BI Connections. HA user is connected but 0 Frames and no Object
4. Task manager shows BI at roughly 4%
5. Opened the Overview HA dashboard but haven't scrolled down so no cameras are in view. Still 4%, 0 Frames, no Object
6. Scrolled down to see the cameras
7. Cameras loaded and CPU jumps around from 4% to 13% depending upon which camera is in the Object column. Frames and Object column are cycling depending upon which is updating
8. Close the HA browser tab
9. CPU back to 4% consistently
10. Frames and Object don't change. I believe they will eventually clear out
11. Open UI3 in a browser. CPU goes to 5%. The user shows up in BI Connections with a Frame value and Object=Index


What I am seeing I don't consider unexpected. HA Overview is loading connections per camera* vs UI3 that is showing the single Index camera so there is going to be a difference in server load.

*I don't know if it truly is cycling for updates or if they are all updating constantly and BI Connection can only show one at a time due to the way the Connection UI is structured

My details (here is where it's going to be near impossible to get a baseline for this):

Integration: H264 with Support Stream unchecked
13 hardwired cameras, 1 wireless. Hardware decode = Intel+VPP
i9 10900K @ 4.8-4.9GHz, 32GB ram
HA is running on this box also via VirtualBox

**Comment by edalquist** [comment] 2022-05-14 20:50
Seeing the same issue, the HA stream connection to BI is a massive CPU drain. Unchecking the stream option in the config doesn't appear to fix things either.

**Comment by kramttocs** [comment] 2022-05-17 15:21
Do you have any other information that might help track this down?
As I am not seeing it (see post above yours) I don't know how to address this.

**Comment by Ming-A** [comment] 2022-10-05 14:03
Having a similar issue when streaming cameras from HA, but I don't think its an integration issue. When I stream 7 RTSP streams together on frigate as well, it would bring my CPU from 5% to max 100%

**Comment by kramttocs** [comment] 2022-10-05 14:11
Thanks @Ming-A .
There have been a few ideas and things that worked for one user but didn't for another in this thread but I don't feel confident that anything points to a defect in the integration.
I am going to close this ticket but if anyone that sees the problem is able to provide more information that indicates an issue with the integration, I welcome them to do so.
I strongly suggest checking with another software (like frigate) or even engaging BlueIris support also to gather more data points.

**Closed by kramttocs** 2022-10-05 14:11 UTC
