### ISSUE TITLE
Allow MOTION binary sensor auto-creation to detect MOTION_<x> Topics

### ISSUE THREAD

**Issue by Hisma** [elad-bar/ha-blueiris#11] opened 2019-05-19 03:39 UTC
It took me hours to figure out why my motion detect sensors were not working.  I checked my mosquitto live database, and found that when motion was detected on a camera, the topic was "~/MOTION_A ON", not "~/MOTION ON", which is what the binary sensor created by this component is expecting to see.  
Because blue iris allows the use of motion groups, it defaults to motion group A in my system.  I changed line 52 in binary_sensor.py from this - 
`for t in ['MOTION', 'AUDIO', 'EXTERNAL', 'WATCHDOG']:`
to this - 
`for t in ['MOTION_A', 'AUDIO', 'EXTERNAL', 'WATCHDOG']:`

Once I did that, my motion detectors worked correctly.

**Comment by darkgrue** [comment] 2019-06-02 17:09
This is a duplicate of Issue #10.

Be aware that there are something like **8!** combinations of motion zones (i.e. 40,320+ sensors per camera). Automatically creating them isn't practical.

I've fixed it in a fork, but until Version 5 was released, we didn't want to keep speculating on how BI was going to handle the MQTT macros. Apparently it's the same.

Auto-creating the `MOTION_A` sensor is the compromise. The end-user can always create MQTT binary sensors for any other motion zones they want to montior in their YAML configuration.

**Closed** 2019-10-01 07:48 UTC
