### ISSUE TITLE
500 Error when trying to configure the integration

### ISSUE THREAD

**Issue by thestigjr** [elad-bar/ha-blueiris#231] opened 2024-06-06 19:35 UTC
![500error](https://github.com/elad-bar/ha-blueiris/assets/116460117/f9cb2ad1-64c6-4579-8826-4594986b63dc)
I receive this error when trying to add the integration to my Home Assistant instance. These are the logs that show when I try to add the integration
```
Logger: aiohttp.server
Source: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:421
First occurred: 12:33:28 PM (1 occurrences)
Last logged: 12:33:28 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 70, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 172, in post
    return await self._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 179, in _post_impl
    return await super()._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 84, in _post_impl
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1262, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1292, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/blueiris/config_flow.py", line 39, in async_step_user
    await self._config_flow.initialize(self.hass)
  File "/config/custom_components/blueiris/managers/config_flow_manager.py", line 63, in initialize
    await self.update_data(data, CONFIG_FLOW_INIT)
  File "/config/custom_components/blueiris/managers/config_flow_manager.py", line 97, in update_data
    await self._update_entry()
  File "/config/custom_components/blueiris/managers/config_flow_manager.py", line 240, in _update_entry
    entry = ConfigEntry(
            ^^^^^^^^^^^^
TypeError: ConfigEntry.__init__() missing 1 required keyword-only argument: 'unique_id'
```

**Comment by kramttocs** [comment] 2024-06-06 20:08
Are you on the beta also?

**Comment by thestigjr** [comment] 2024-06-06 20:34
I don't believe so, i'm on version 1.0.18

**Comment by sharri46** [comment] 2024-06-07 00:19
This seems tk happen to me with the new core update. It breaks this Integration...

**Comment by thestigjr** [comment] 2024-06-07 04:09
Glad i'm not the only one, It should be said that i had this integration working for a while, and i just recently added more cameras and wasn't able to reconfigure it, which sent me down a path of uninstalling/clearing out files.

**Comment by Raptor607** [comment] 2024-06-07 14:01
Experiencing this issue as well since core update.

**Comment by kramttocs** [comment] 2024-06-07 14:11
Closing this one as a duplicate of https://github.com/elad-bar/ha-blueiris/issues/230 that showed up on the dev/beta.

Acknowledge that it's a significant issue and will look at it as soon as I can to see what can be done. Thanks

**Closed by kramttocs** 2024-06-07 14:11 UTC
