### ISSUE TITLE
FEATURE REQUEST: Control Camera Motion (On/Off)

### ISSUE THREAD

**Issue by RJ-Make** [elad-bar/ha-blueiris#164] opened 2022-04-03 16:10 UTC
An entity to switch a camera's motion (Trigger Option) on or off. (and to retrieve its current status)

**Comment by kramttocs** [comment] 2022-04-04 12:53
I like this idea. Will look into it.

**Comment by RJ-Make** [comment] 2022-11-25 15:18
Any movement on this?

**Comment by kramttocs** [comment] 2022-11-25 15:37
Sorry, no. I haven't had luck adding a new entity especially per camera.

BI has a camconfig command with motion having the definition of: true/false, enable/disable the motion detector for the currently effective profile

So that should be able to be used.

**Comment by RJ-Make** [comment] 2022-11-26 11:33
Ok, Thanks! I figured out how to achieve this is yesterday with command_line. A bit of work for a single functions but sometime you have to do what you have to do? :-)

For others

In my config yaml
```
switch:
  - platform: command_line
    switches:
      inside_rear_camera_motion:
        unique_id: '12345irlcameramotion'
        command_on: !secret BI_IR1_Motion_On
        command_off: !secret BI_IR1_Motion_Off
```
Secrets
```
BI_IR1_Motion_On: "curl -k 'http://192.168.1.26:81/admin?camera=IR1&motion=1&user=USERNAME&pw=PASSWORD'"
BI_IR1_Motion_Off: "curl -k 'http://192.168.1.26:81/admin?camera=IR1&motion=0&user=USERNAME&pw=PASSWORD'"
```

**Comment by kramttocs** [comment] 2022-11-26 13:52
Thanks for posting that for others.

I could create a service that takes a camera device and True/False that allows you to turn it on and off if you'd like. Wouldn't allow one to see the status though, only change it.

I just for the life of me can't wrap my head around creating an entity under the camera device and syncing it with BI.
I'd really like to though because once I can do on, there are a lot of settings in BI we could control.

**Comment by kramttocs** [comment] 2022-12-05 07:26
Closing as a duplicate of https://github.com/elad-bar/ha-blueiris/issues/109
Discussion can continue there

**Closed by kramttocs** 2022-12-05 07:26 UTC
Labels: enhancement
